name: ayon-hub
services:
- name: server
  environment_slug: docker
  dockerfile_path: Dockerfile
  github:
    repo: V-Sekai/ayon-docker
    branch: main
  health_check:
    http_path: /api/info
  envs:
  - key: POSTGRES_USER
    value: ${POSTGRES_USER}
    scope: RUN_AND_BUILD_TIME
  - key: POSTGRES_PASSWORD
    value: ${POSTGRES_PASSWORD}
    scope: RUN_AND_BUILD_TIME
  - key: POSTGRES_DB
    value: ${POSTGRES_DB}
    scope: RUN_AND_BUILD_TIME
  routes:
  - path: /
